[build]
  # Directorio donde se colocan los archivos de salida de la aplicaci칩n
  publish = "build"
  # Comando que Netlify debe ejecutar para construir el sitio
  command = "npm run build"

  # Configuraci칩n de variables de entorno
  [build.environment]
    NODE_VERSION = "18"

# Definici칩n de funciones si est치s usando funciones serverless (opcional)
[functions]
  directory = "functions"
