[build]
  publish = "build"
  command = "npm run build"

  [build.environment]
    PYTHON_VERSION = "3.9"
    NODE_VERSION = "18"

# Definición de funciones para un backend simple (si tienes algún archivo en la carpeta "functions")
[functions]
  directory = "functions"
